### ISSUE TITLE
BUG: Alloy fails to parse and solve the expression

### ISSUE THREAD

**Issue by kaiyuanw** [AlloyTools/org.alloytools.alloy#18] opened 2017-11-12 15:41 UTC
Alloy4.2 fails to run the following check.  I've checked a number of old Alloy versions and it seems this problem exists from the beginning.

```Alloy
module grandpa

abstract sig Person {}

sig Man extends Person { wife: lone Woman }

sig Woman extends Person { husband: lone Man }

check { no *(wife+husband)} for 1
```

**Comment by pkriens** [comment] 2017-11-17 10:02
not sure what the problem is. It finds a counter example when # Woman = 0 or # Man = 0?

**Comment by pkriens** [comment] 2018-03-05 17:54
Closing for no answer

**Closed by pkriens** 2018-03-05 17:54 UTC
Labels: question
