### ISSUE TITLE
Linux Display & Font issues

### ISSUE THREAD

**Issue by ocharles** [AlloyTools/org.alloytools.alloy#119] opened 2020-05-14 12:47 UTC
I'm trying to use Alloy from Linux on a 4k monitor. All of the usual options to get HiDPI working don't seem to affect alloy. I've tried:

* Setting `GDK_SCALE` to `2`
* Running with `-Dsun.java2d.uiScale=2`
* Running with `-Dglass.gtk.uiScale=2`

but there is no change.

This is how my UI currently looks (with a custom set font):

![image](https://user-images.githubusercontent.com/20878/81935894-3e198580-95e9-11ea-94f3-6389006b463a.png)

Thankfully the most important information is readable, but using the visualiser is hard because I can barely read the layout editor!

![image](https://user-images.githubusercontent.com/20878/81936001-630df880-95e9-11ea-9b7f-09ebd4a04010.png)

**Comment by pkriens** [comment] 2020-05-14 16:14
Did you try Java 9?

According to https://bugs.openjdk.java.net/browse/JDK-8137571 <https://bugs.openjdk.java.net/browse/JDK-8137571> this support was implemented in Java 1.9.

We've not tested Alloy on 1.9 and it does not work on my Mac, but it might be your best bet.

**Comment by MarkoSchuetz** [comment] 2020-08-06 17:05
I have the same issue. I tried OpenJDK 7, 8, 10, 11, and 14. None of the 3 variants mentioned in the OP has the desired effect.
As a work-around I use `run_scaled` from here [https://github.com/kaueraal/run_scaled]. It does work somewhat: sometimes the mouse pointer location inside menus is shifted.

**Comment by pkriens** [comment] 2021-12-23 18:56
I've designated this as thee primary bug for Linux display issues.

**Comment by awwx** [comment] 2022-03-06 19:27
fyi `-Dsun.java2d.uiScale=2` is working for me with Alloy 6.1.0, OpenJDK 11.0.12, Ubuntu 21.04

**Comment by pkriens** [comment] 2023-03-01 19:20
@ocharles (and others) if you use  -Dsun.java2d.uiScale=2, does this work for you?

**Comment by pkriens** [comment] 2023-04-14 14:52
Closing because no reply

**Closed by pkriens** 2023-04-14 14:52 UTC
Labels: bug

**Comment by MarkoSchuetz** [comment] 2023-04-15 15:04
I can confirm that Java 19 with  `-Dsun.java2d.uiScale=2` makes menu fonts and icons twice as large. This makes it more usable, however the graphical elements are then quite oversized and take up very much screen real-estate.
